### PR TITLE
add a commonNav option to set nav html code in one file only

### LINKED ISSUE #75: [enhancement wish] common nav for all html pages
Hi,

On a quite big js project, generated documentation is 1224 files of 2Mo each (2,3Go). It's because the <nav> part has a weight of 1.9Mo.

Having only one `<nav>` content for all files could reduce a lot the total weight, here around 200 times less (`1224×2000` vs `1900 + 1224×100`, in my case from 2.3Go to ~125Mo).

It could be done with a frameset, or an ajax call to populate the nav bar in each html page (the nav.html will be in the browser cache after the first call).

Is such an enhancement can be put on the roadmap ?

BTW, thanks a lot for this great template.

### PR DESCRIPTION
**Pull request by dcaillibaud**
The nav html code is fetched after each page loading (instead of being embedded), in my case total doc weight get reduced from 2.3Go to 40Mo (2Mo for nav.inc.html, 600k html pages).

Close #75

### CODE REVIEW

**Comment by dcaillibaud** [comment]
Feel free to change the "commonNav" name (it's the only one in camelCase, perhaps not a good idea).

**Comment by laramurphyyx** [comment]
This is really helpful! Do you plan to have a release for this soon?

**Comment by dcaillibaud** [comment]
> This is really helpful!
Thanks ;-)

> Do you plan to have a release for this soon?

It's already released (since at least 1.2.0) => ar2rsawseen merged 2 commits into clenemt:master from dcaillibaud:addCommonNavOption on 20 Apr

Before this merge I put in my package.json
`  "docdash": "github:dcaillibaud/docdash#addCommonNavOption",`
but I rollback to a more usual config with
`  "docdash": "^1.2.0",`
for a while.

**Comment by laramurphyyx** [comment]
Thanks for getting back to me so quickly!

At the moment, I'm currently consuming docdash ^1.2.0 within my package.json from npm but unfortunately can't see the new features you've included in PR #95. I've looked at the github release - https://github.com/clenemt/docdash/releases/tag/1.2.0 - and it doesn't say this feature is included. It seems the 1.2 version was released on 26/01/2020 but this PR was only merged on 20/04/2021. I assumed that this did not contain the new feature, is this the case?

The github release version 1.2.0 seems to be the same as the public npm version 1.2.0 - https://www.npmjs.com/package/docdash/v/1.2.0 - which also does not include the feature. 

I've pulled down docdash master locally and verified the feature works perfectly (great job 👍 ), so I'm just looking for clarification as to the plan for the associated npm release it's planned to be contained in.

Any help would be appreciated, would love to use this feature. Thanks!

**Pull request merged**
