### PR TITLE
Added menu search and collapse options as well as numerous other meta data options and disqus support

### PR DESCRIPTION
**Pull request by ar2rsawseen**

### CODE REVIEW

**Comment by develar** [comment]
@ar2rsawseen I have applied your PR to my fork, but search works only for methods, not for class names.

**Comment by ar2rsawseen** [comment]
Hello,
thanks for feedback, will recheck.
But we probably can consider this repo dead, right?

**Comment by develar** [comment]
> But we probably can consider this repo dead, right?

I am just user :) Dead because @clenemt doesn't maintain this anymore or there is a successor?

**Comment by clenemt** [comment]
I will a take a look at open pr this weekend, sorry for the delay.

**Comment by ar2rsawseen** [comment]
Hey @clenemt no problem, we all have a life :)

**Comment by ar2rsawseen** [comment]
@develar fixed your issue and added 2 more features
config to include typedefs in menu
config to remove quotes from pathnames

**Comment by develar** [comment]
@ar2rsawseen Thanks! It works (e.g. http://electron-userland.github.io/electron-builder/).

**Comment by diegosebgonz** [comment]
clement is possible added this solution to the master branch?

**Comment by nabeelz6** [comment]
Looks like this could be merged now?

**Comment by ar2rsawseen** [comment]
With approval from author, finally we decided to go with our own version of this repo and published it as npm package. Feel free to check it out and send your PRs there.
https://www.npmjs.com/package/countly-docdash

**Pull request merged**
