### PR TITLE
removes arbitrary width property

### PR DESCRIPTION
**Pull request by gabrielcsapo**
> problem here https://github.com/gabrielcsapo/node-git-server/pull/25#issuecomment-343052842

| before | after |
|--------|-----|
|  32589396-22399ef0-c50c-11e7-8ef8-16a7daab401d | screen shot 2017-11-08 at 10 00 25 pm |

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
With approval from author, finally we decided to go with our own version of this repo and published it as npm package. Feel free to check it out and send your PRs there.
https://www.npmjs.com/package/countly-docdash

**Comment by gabrielcsapo** [comment]
@ar2rsawseen I think it would have been better to jus maintain this repo, but will open my PR against your new package.

**Comment by clenemt** [comment]
@ar2rsawseen if you want I can give you access to this repo if you feel like maintaining this instead of creating a new one. Let me know 👍

**Comment by ar2rsawseen** [comment]
That's a possibility we considered, yes, but we are interested in the template from company perspective, all internal docs on it, and now want to produce external ones too, etc. And while currently I am only one dedicated to it, it might change and future, and as with every company new employees join and go, and adding/removing each and every one of them would be tiresome for you. But since we already control access on our account for teams, it will be easier for us.

Other way this could work, is, if you are willing to transfer ownership of repo to our account, but then again it would probably mess up npm packages and would need to publish new one either way. That's why we decided to go this way, hope everyone understands :)

**Comment by gabrielcsapo** [comment]
Props to @clenemt +1

**Comment by clenemt** [comment]
@ar2rsawseen you are now a collaborator, you should be able to mark this repo as deprecated and redirect to your own in the README. Good luck out there 👍

**Comment by ar2rsawseen** [comment]
@clenemt if you can add me on npm too, we can try to manage this repo with same npm package then

**Comment by hugolpz** [comment]
@clenemt, please see #98. Time for more maintainers !

**Pull request merged**
