### PR TITLE
Add support for @sig and @category tags

### PR DESCRIPTION
**Pull request by char0n**
I needed support for new tags @sig and @category to be able to generate ramda like docs.
Here is the source for jsdoc plugins:

```javascript
'use strict';

exports.defineTags = (dictionary) => {
  dictionary.defineTag('sig', {
    mustHaveValue: true,
    canHaveType: false,
    canHaveName: false,
    onTagged(doclet, tag) {
      doclet.sig = tag.value;
    },
  });

  dictionary.defineTag('category', {
    mustHaveValue: true,
    canHaveType: false,
    canHaveName: false,
    onTagged(doclet, tag) {
      doclet.category = tag.value;
    },
  });
};
```

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
With approval from author, finally we decided to go with our own version of this repo and published it as npm package. Feel free to check it out and send your PRs there.
https://www.npmjs.com/package/countly-docdash

**Comment by ar2rsawseen** [comment]
Hello,
if you are still willing to give this PR ago, I would happily review and merge it
but since currently theme has changed, it already has searching and collapsing menu, etc. I think it would be better to start over, so closing this PR.

**Comment by char0n** [comment]
Is there a separate repo  for this or are we using the same github repo as before ?

**Comment by ar2rsawseen** [comment]
Everyone voted for using the same, since I got access to this repo, let's use this one :)

**Pull request closed without merging**
