### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by rugk**
Fixes https://github.com/clenemt/docdash/issues/53

I've only tested it partially in browser, but I may do a full test later.

Also, I really just transferred the jQuery logic 1:1, you can see it is often very suboptimal and could be imroved.
Expect a few pushes again.

And I do see it as a big improvment to get rid of this big, big library for just 200 LOC...

### CODE REVIEW

**Comment by rugk** [comment]
And and BTW, I've tested docdash in IE, and I guess we do not have to worry here; the whole site (CSS) is broken there anyway (note this is your unmodified example):
grafik

So can we drop IE support?

**Comment by ar2rsawseen** [comment]
It only means none of the current users use IE. 😃  But since it has been discovered, I think we will need to address that for at least, as you say, IE9

**Comment by ar2rsawseen** [comment]
Hmm, I just tried and it seems to be working without problems right now

image

**Comment by ar2rsawseen** [comment]
So how about this? Save to merge?

**Comment by rugk** [comment]
If you've tested it, I guess it was. At least theoretically...

**Pull request merged**
